OpenShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace="authentication")),
    path("", include('store.urls', namespace="store")), 
]

if settings.DEBUG:   
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path 
from.import views 

app_name = 'authentication'

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"), 
]

store/urls.py
from django.urls import path
from . import views
app_name = 'store'


urlpatterns = [
    path("", views.home, name="home"),
    path("creer_annonce/", views.creer_annonce, name="creer_annonce"),
    path("categorie/<int:categorie_id>/", views.annonces_par_categorie, name="annonces_par_categorie"),
    path("souscategorie/<int:souscategorie_id>/", views.annonces_par_souscategorie, name="annonces_par_souscategorie"),
    path("get_sous_categories/", views.get_sous_categories, name="get_sous_categories"),
    path('annonce/<int:pk>/', views.detail_annonce, name='detail_annonce')

]

templates/base.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}?v=5">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <title>openshop</title>
</head>
<body>  

    <header>
  <nav class="navbar">
    <div class="logo">
      <a href="{% url 'store:home' %}">OpenShop</a>
    </div>

    <!-- Menu principal -->
    <ul class="nav-links" id="navLinks">
      <li><a href="{% url 'store:creer_annonce' %}">Déposer une annonce</a></li>

      {% if not user.is_authenticated %}
        <li><a href="{% url 'authentication:login' %}">Se connecter</a></li>
        <li><a href="{% url 'authentication:register' %}">S'inscrire</a></li>
      {% else %}
        <li><a href="{% url 'authentication:logout' %}">Se déconnecter</a></li>
      {% endif %}
    </ul>

    <!-- Bouton hamburger -->
    <div class="hamburger" id="hamburger">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </nav>
</header>


 <main>  
         {% block content %}  
         {% endblock %}
</main>

        
<footer class="footer">
  <div class="footer-container">
    <div class="footer-about">
      <h3>Orenda Tech</h3>
      <p>Nous aidons les entreprises et les particuliers en Guinée à booster leur présence digitale à travers des solutions modernes et fiables.</p>
    </div>
    <div class="footer-services">
      <h4>Nos services</h4>
      <ul>
        <li>Création de sites vitrines</li>
        <li>Conception de logos</li>
        <li>Affiches publicitaires</li>
        <li>Hébergement web</li>
      </ul>
    </div>
    <div class="footer-contact">
      <h4>Contact</h4>
      <p>Email : asbarry2468@gmail.com</p>
      <p>Tél : +224 622 95 24 68</p>
      <p>Conakry, Guinée</p>
    </div>
  </div>
  <div class="footer-bottom">
    <p>&copy; 2025 Orenda Tech - Tous droits réservés</p>
  </div>
</footer>


  <script src="{% static 'js/hamburger.js' %}"></script>     
</body>
</html>